"""Shadcn-style installer: copy qt-ai-dev-tools into a project directory."""

from __future__ import annotations

import shutil
import stat
from pathlib import Path

from qt_ai_dev_tools.__version__ import __version__

_PACKAGE_ROOT: Path = Path(__file__).parent

_CLI_SCRIPT_TEMPLATE: str = """\
#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["typer>=0.12.0", "jinja2>=3.1.0", "colorlog>=6.10.1"]
# ///
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))
from qt_ai_dev_tools.cli import app

app()
"""

_CONFIG_TOML_TEMPLATE: str = """\
# qt-ai-dev-tools workspace configuration
# Generated by qt-ai-dev-tools {version}

[workspace]
memory = {memory}
cpus = {cpus}
provider = "libvirt"
box = "bento/ubuntu-24.04"
hostname = "qt-dev"
display = ":99"
resolution = "1920x1080x24"
"""

_PYPROJECT_TOML_TEMPLATE: str = """\
[project]
name = "qt-ai-dev-tools"
version = "{version}"
requires-python = ">=3.12"
dependencies = ["typer>=0.12.0", "jinja2>=3.1.0", "colorlog>=6.10.1"]

[project.scripts]
qt-ai-dev-tools = "qt_ai_dev_tools.cli:app"

[tool.hatch.build.targets.wheel]
packages = ["src/qt_ai_dev_tools"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
"""


def _copy_package_source(target_src: Path) -> None:
    """Copy the qt_ai_dev_tools package source into target/src/."""
    dest = target_src / "qt_ai_dev_tools"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(
        _PACKAGE_ROOT,
        dest,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"),
    )


def _copy_templates(target_templates: Path) -> None:
    """Copy vagrant templates into target/templates/."""
    src_templates = _PACKAGE_ROOT / "vagrant" / "templates"
    if not src_templates.exists():
        return
    if target_templates.exists():
        shutil.rmtree(target_templates)
    shutil.copytree(
        src_templates,
        target_templates,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )


def _copy_skills(target_skills: Path) -> None:
    """Copy skills directory into target/skills/."""
    # Skills live alongside the package root, two levels up from _PACKAGE_ROOT
    # _PACKAGE_ROOT = src/qt_ai_dev_tools/ -> project root = ../../
    project_root = _PACKAGE_ROOT.parent.parent
    src_skills = project_root / "skills"
    if not src_skills.exists():
        return
    if target_skills.exists():
        shutil.rmtree(target_skills)
    shutil.copytree(
        src_skills,
        target_skills,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )


def _write_cli_script(target: Path) -> Path:
    """Generate the cli shebang script."""
    cli_path = target / "cli"
    cli_path.write_text(_CLI_SCRIPT_TEMPLATE)
    cli_path.chmod(cli_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return cli_path


def _write_pyproject_toml(target: Path) -> Path:
    """Generate pyproject.toml for uv tool install compatibility.

    Copies the project's real pyproject.toml when available (git checkout).
    Falls back to a minimal template when installed from PyPI (wheel).
    """
    pyproject_path = target / "pyproject.toml"
    # Try to copy the real pyproject.toml from the project root
    project_root = _PACKAGE_ROOT.parent.parent
    source_pyproject = project_root / "pyproject.toml"
    if source_pyproject.is_file():
        pyproject_path.write_text(source_pyproject.read_text(encoding="utf-8"), encoding="utf-8")
    else:
        # Fallback: minimal template for PyPI installs
        pyproject_path.write_text(_PYPROJECT_TOML_TEMPLATE.format(version=__version__))
    return pyproject_path


def _write_config_toml(target: Path, *, memory: int, cpus: int) -> Path:
    """Generate config.toml with workspace defaults."""
    config_path = target / "config.toml"
    config_path.write_text(_CONFIG_TOML_TEMPLATE.format(version=__version__, memory=memory, cpus=cpus))
    return config_path


def install_and_own(target: Path, *, memory: int = 4096, cpus: int = 4) -> list[str]:
    """Install qt-ai-dev-tools toolkit into a project directory (shadcn-style).

    Creates the directory structure, copies source, templates, skills,
    and generates config files.

    Args:
        target: Target directory to install into.
        memory: VM memory in MB.
        cpus: VM CPU count.

    Returns:
        List of created/updated paths (relative to target).
    """
    created: list[str] = []

    # Create directory structure
    for subdir in ("src", "templates", "skills", "notes"):
        (target / subdir).mkdir(parents=True, exist_ok=True)
        created.append(f"{subdir}/")

    # Copy package source
    _copy_package_source(target / "src")
    created.append("src/qt_ai_dev_tools/")

    # Copy templates
    _copy_templates(target / "templates")
    created.append("templates/")

    # Copy skills
    _copy_skills(target / "skills")
    created.append("skills/")

    # Generate CLI script
    _write_cli_script(target)
    created.append("cli")

    # Generate config.toml
    _write_config_toml(target, memory=memory, cpus=cpus)
    created.append("config.toml")

    # Generate pyproject.toml (enables `uv tool install` from this directory)
    _write_pyproject_toml(target)
    created.append("pyproject.toml")

    return created


def self_update(target: Path) -> list[str]:
    """Re-run init, preserving config.toml, notes/, and modified templates.

    Args:
        target: Existing toolkit directory to update.

    Returns:
        List of updated paths (relative to target).
    """
    if not target.exists():
        msg = f"Target directory does not exist: {target}"
        raise FileNotFoundError(msg)

    # Preserve user data
    config_path = target / "config.toml"
    config_backup: str | None = None
    if config_path.exists():
        config_backup = config_path.read_text()

    notes_dir = target / "notes"
    notes_backup: Path | None = None
    if notes_dir.exists():
        notes_backup = target / "_notes_backup"
        if notes_backup.exists():
            shutil.rmtree(notes_backup)
        shutil.copytree(notes_dir, notes_backup)

    # Re-run install with defaults (config will be overwritten, then restored)
    updated = install_and_own(target)

    # Restore preserved data
    if config_backup is not None:
        config_path.write_text(config_backup)

    if notes_backup is not None:
        if notes_dir.exists():
            shutil.rmtree(notes_dir)
        shutil.copytree(notes_backup, notes_dir)
        shutil.rmtree(notes_backup)

    return updated
